---
- name: Provision EC2 instance and install Docker
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    instance_name: Rewardz
  tasks:
    - name: Create EC2 instance
      ec2:
        key_name: AWS
        instance_type: t2.micro
        image: ami-01a4f99c4ac11b03c
        region: ap-south-1
        vpc_subnet_id: subnet-0f78abbe5ded6ee3e
        assign_public_ip: yes

    - name: Install Docker
      become: true
      package:
        name: docker
        state: present

    - name: Start Docker service
      become: true
      service:
        name: docker
        state: started

    - name: Pull the latest WordPress image
      become: true
      command: docker pull wordpress

    - name: Create a Docker container with WordPress
      become: true
      command: docker run --name Rewardz-assign -p 9090:80 -d wordpress

    - name: Wait for the container to start
      become: true
      wait_for:
        port: 9090
        state: started
